export interface Option {
    value: string;
    label: string;
}
export const DistritosporProvincia:Record<string, Option[]> = {
    Chachapoyas: [
        { value: 'Asunción', label: 'Asunción' },
        { value: 'Balsas', label: 'Balsas' },
        { value: 'ChachaPoyas', label: 'ChachaPoyas' },
        { value: 'Cheto', label: 'Cheto' },
        { value: 'Chiliquín', label: 'Chiliquín' },
        { value: 'Chuquibamba', label: 'Chuquibamba' },
        { value: 'Granada', label: 'Granada' },
        { value: 'Huancas', label: 'Huancas' },
        { value: 'Jalca Grande', label: 'Jalca Grande' },
        { value: 'Leimebamba', label: 'Leimebamba' },
        { value: 'Levanto', label: 'Levanto' },
        { value: 'Magdalena', label: 'Magdalena' },
        { value: 'Mariscal Castilla', label: 'Mariscal Castilla' },
        { value: 'MolinoPampa', label: 'MolinoPampa' },
        { value: 'Montevideo', label: 'Montevideo' },
        { value: 'Olleros', label: 'Olleros' },
        { value: 'Quinjalca', label: 'Quinjalca' },
        { value: 'San Francisco de Daguas', label: 'San Francisco de Daguas' },
        { value: 'San Isidro de Maino', label: 'San Isidro de Maino' },
        { value: 'Soloco', label: 'Soloco' },
        { value: 'Sonche', label: 'Sonche' },

    ],
    Bagua: [
        { value: 'Bagua', label: 'Bagua' },
        { value: 'La Peca', label: 'La Peca' },
        { value: 'Aramango', label: 'Aramango' },
        { value: 'Copallín', label: 'Copallín' },
        { value: 'El Parco', label: 'El Parco' },
        { value: 'Chiriaco', label: 'Chiriaco' },
    ],
    Bongorá: [
        { value: 'Jumbilla', label: 'Jumbilla' },
        { value: 'Chisquilla', label: 'Chisquilla' },
        { value: 'Churuja', label: 'Churuja' },
        { value: 'Corosha', label: 'Corosha' },
        { value: 'Cuispes', label: 'Cuispes' },
        { value: 'Florida', label: 'Florida' },
        { value: 'Jazán', label: 'Jazán' },
        { value: 'Recta', label: 'Recta' },
        { value: 'San Carlos', label: 'San Carlos' },
        { value: 'Shipasbamba', label: 'Shipasbamba' },
        { value: 'Valera', label: 'Valera' },
        { value: 'Yambrasbamba', label: 'Yambrasbamba' },
    ],
    Condorcanqui: [
        { value: 'El Cenepa', label: 'El Cenepa' },
        { value: 'Nieva', label: 'Nieva' },
        { value: 'Río Santiago', label: 'Río Santiago' },
    ],
    Luya: [
        { value: 'Caporredondo', label: 'Caporredondo' },
        { value: 'Cocabamba', label: 'Cocabamba' },
        { value: 'Colcamar', label: 'Colcamar' },
        { value: 'Conila', label: 'Conila' },
        { value: 'Inguilpata', label: 'Inguilpata' },
        { value: 'Lámud', label: 'Lámud' },
        { value: 'Longuita', label: 'Longuita' },
        { value: 'Lonya Chico', label: 'Lonya Chico' },
        { value: 'Luya', label: 'Luya' },
        { value: 'Luya Viejo', label: 'Luya Viejo' },
        { value: 'María', label: 'María' },
        { value: 'Ocalli', label: 'Ocalli' },
        { value: 'Ocumal', label: 'Ocumal' },
        { value: 'Pisuquía', label: 'Pisuquía' },
        { value: 'Providencia', label: 'Providencia' },
        { value: 'San Cristobal', label: 'San Cristobal' },
        { value: 'San Francisco del Yeso', label: 'San Francisco del Yeso' },
        { value: 'San Jerónimo', label: 'San Jerónimo' },
        { value: 'San Juan de Lopecancha', label: 'San Juan de Lopecancha' },
        { value: 'Santa Catalina', label: 'Santa Catalina' },
        { value: 'Santo Tomás', label: 'Santo Tomás' },
        { value: 'Tingo', label: 'Tingo' },
        { value: 'Trita', label: 'Trita' },
    ],
    'Rodriguez de mendoza': [
        { value: 'San Nicolás', label: 'San Nicolás' },
        { value: 'Chirimoto', label: 'Chirimoto' },
        { value: 'Cochamal', label: 'Cochamal' },
        { value: 'Huambo', label: 'Huambo' },
        { value: 'Limabamba', label: 'Limabamba' },
        { value: 'Longar', label: 'Longar' },
        { value: 'Mariscal Benavides', label: 'Mariscal Benavides' },
        { value: 'Mílpuc', label: 'Mílpuc' },
        { value: 'Omia', label: 'Omia' },
        { value: 'Santa Rosa', label: 'Santa Rosa' },
        { value: 'Totora', label: 'Totora' },
        { value: 'Vista Alegre', label: 'Vista Alegre' },
    ],
    Utcubamba: [
        { value: 'Bagua Grande', label: 'Bagua Grande' },
        { value: 'Cajaruro', label: 'Cajaruro' },
        { value: 'Cumba', label: 'Cumba' },
        { value: 'El Milagro', label: 'El Milagro' },
        { value: 'Jamalca', label: 'Jamalca' },
        { value: 'Lonya Grande', label: 'Chirimoto' },
        { value: 'Yamón', label: 'Yamón' },
    ],
    //Ancash////
    Aija: [
        { value: 'Aija', label: 'Aija' },
        { value: 'Coris', label: 'Coris' },
        { value: 'Huacllán', label: 'Huacllán' },
        { value: 'La Merced', label: 'La Merced' },
        { value: 'Succha', label: 'Succha' },
    ],
    'Antonio Raymondi': [
        { value: 'Llamellín', label: 'Llamellín' },
        { value: 'Aczo', label: 'Aczo' },
        { value: 'Chacco', label: 'Chacco' },
        { value: 'Chingas', label: 'Chingas' },
        { value: 'Mirgas', label: 'Mirgas' },
        { value: 'San Juan de Rontoy', label: 'San Juan de Rontoy' },
    ],
    Asuncion: [
        { value: 'Chacas', label: 'Chacas' },
        { value: 'Acochaca', label: 'Acochaca' },
    ],
    Bolognesi: [
        { value: 'Abelardo Pardo Lezameta', label: 'Abelardo Pardo Lezameta' },
        { value: 'Antonio Raimondi', label: 'Antonio Raimondi' },
        { value: 'Aquia', label: 'Aquia' },
        { value: 'Cajacay', label: 'Cajacay' },
        { value: 'Canis', label: 'Canis' },
        { value: 'Chiquian', label: 'Chiquian' },
        { value: 'Cólquioc', label: 'Cólquioc' },
        { value: 'Huallanca', label: 'Huallanca' },
        { value: 'Huasta', label: 'Huasta' },
        { value: 'Huayllacayán', label: 'Huayllacayán' },
        { value: 'La Primavera', label: 'La Primavera' },
        { value: 'Mangas', label: 'Mangas' },
        { value: 'Pacllón', label: 'Pacllón' },
        { value: 'San Miguel de Corpanqui', label: 'Pacllón' },
        { value: 'Pacllón', label: 'Pacllón' },
        { value: 'San Miguel de Corpanqui', label: 'San Miguel de Corpanqui' },
        { value: 'Ticllos', label: 'Ticllos' },
    ],
    Carhuaz: [
        { value: 'Carhuaz', label: 'Carhuaz' },
        { value: 'Acopampa', label: 'Acopampa' },
        { value: 'Amashaca', label: 'Amashaca' },
        { value: 'Anta', label: 'Anta' },
        { value: 'Ataquero', label: 'Ataquero' },
        { value: 'Marcará', label: 'Marcará' },
        { value: 'Pariahuanca', label: 'Pariahuanca' },
        { value: 'San Miguel de Aco', label: 'San Miguel de Aco' },
        { value: 'Shilla', label: 'Shilla' },
        { value: 'Tinco', label: 'Tinco' },
        { value: 'Yungar', label: 'Yungar' },
    ],
    'Carlos Fitzcarrald': [
        { value: 'San Luis', label: 'San Luis' },
        { value: 'San Nicolás', label: 'San Nicolás' },
        { value: 'Yauya', label: 'Yauya' },
    ],
    Casma: [
        { value: 'Casma', label: 'Casma' },
        { value: 'Buenavista Alta', label: 'Buenavista Alta' },
        { value: 'Comandante Noel', label: 'Comandante Noel' },
        { value: 'Yaután', label: 'Yaután' },
    ],
    Corongo: [
        { value: 'Corongo', label: 'Corongo' },
        { value: 'Aco', label: 'Aco' },
        { value: 'Bambas', label: 'Bambas' },
        { value: 'Cusca', label: 'Cusca' },
        { value: 'La Pampa', label: 'La Pampa' },
        { value: 'Yánac', label: 'Yánac' },
        { value: 'Yupán', label: 'Yupán' },
    ],
    Huaraz: [
        { value: 'Huaraz', label: 'Huaraz' },
        { value: 'Cochabamba', label: 'Cochabamba' },
        { value: 'Huanchay', label: 'Huanchay' },
        { value: 'Independencia', label: 'Independencia' },
        { value: 'La Libertad', label: 'La Libertad' },
        { value: 'Olleros', label: 'Olleros' },
        { value: 'Pampas Grande', label: 'Pampas Grande' },
        { value: 'Pariacoto', label: 'Pariacoto' },
        { value: 'Pira', label: 'Pira' },
        { value: 'Tarica', label: 'Tarica' },
    ],
    Huari: [
        { value: 'Huari', label: 'Huari' },
        { value: 'Anra', label: 'Anra' },
        { value: 'Cajay', label: 'Cajay' },
        { value: 'Chavín de Huántar', label: 'Chavín de Huántar' },
        { value: 'Huacachi', label: 'Huacachi' },
        { value: 'Huacchis', label: 'Huacchis' },
        { value: 'Huachis', label: 'Huachis' },
        { value: 'Huántar', label: 'Huántar' },
        { value: 'Masin', label: 'Masin' },
        { value: 'Paucas', label: 'Paucas' },
        { value: 'Pontó', label: 'Pontó' },
        { value: 'Rahuapampa', label: 'Rahuapampa' },
        { value: 'Rapayán', label: 'Rapayán' },
        { value: 'San Marcos', label: 'San Marcos' },
        { value: 'San Pedro de Chaná', label: 'San Pedro de Chaná' },
        { value: 'Uco', label: 'Uco' },
    ],
    Huarmey: [
        { value: 'Huarmey', label: 'Huarmey' },
        { value: 'Cochapeti', label: 'Cochapeti' },
        { value: 'Culebras', label: 'Culebras' },
        { value: 'Huayán', label: 'Huayán' },
        { value: 'Malvas', label: 'Malvas' },
    ],
    Huaylas: [
        { value: 'Caraz', label: 'Caraz' },
        { value: 'Huallanca', label: 'Huallanca' },
        { value: 'Huata', label: 'Huata' },
        { value: 'Huaylas', label: 'Huaylas' },
        { value: 'Mato', label: 'Mato' },
        { value: 'Pamparomás', label: 'Pamparomás' },
        { value: 'Yuracmarca', label: 'Yuracmarca' },
    ],
    'Mariscal Luzuriaga': [
        { value: 'Piscobamba', label: 'Piscobamba' },
        { value: 'Casca', label: 'Casca' },
        { value: 'Eleazar Guzmán Barrón', label: 'Eleazar Guzmán Barrón' },
        { value: 'LLama', label: 'LLama' },
        { value: 'Llumpa', label: 'Llumpa' },
        { value: 'Musga', label: 'Musga' },
        { value: 'Lucma', label: 'Lucma' },
    ],
    Ocros: [
        { value: 'Ocros', label: 'Ocros' },
        { value: 'Acas', label: 'Acas' },
        { value: 'Cajamarquilla', label: 'Cajamarquilla' },
        { value: 'Carhuapampa', label: 'Carhuapampa' },
        { value: 'Cochas', label: 'Cochas' },
        { value: 'Congas', label: 'Congas' },
        { value: 'Llipa', label: 'Llipa' },
        { value: 'San Cristóbal de Raján', label: 'San Cristóbal de Raján' },
        { value: 'San Pedro', label: 'San Pedro' },
        { value: 'Santiago de Chilcas', label: 'Santiago de Chilcas' },
    ],
    Pallasca: [
        { value: 'Cabana', label: 'Cabana' },
        { value: 'Bolognesi', label: 'Bolognesi' },
        { value: 'Conchucos', label: 'Conchucos' },
        { value: 'Huacaschuque', label: 'Huacaschuque' },
        { value: 'Huandoval', label: 'Huandoval' },
        { value: 'Lacabamba', label: 'Lacabamba' },
        { value: 'Llapa', label: 'Llapa' },
        { value: 'Pallasca', label: 'Pallasca' },
        { value: 'Pampas', label: 'Pampas' },
        { value: 'Santa Rosa', label: 'Santa Rosa' },
        { value: 'Tauca', label: 'Tauca' },
    ],
    Pomabamba: [
        { value: 'Pomabamba', label: 'Pomabamba' },
        { value: 'Huayllán', label: 'Huayllán' },
        { value: 'Parobamba', label: 'Parobamba' },
        { value: 'Quinuabamba', label: 'Quinuabamba' },
    ],
    Recuay: [
        { value: 'Recuay', label: 'Recuay' },
        { value: 'Cátac', label: 'Cátac' },
        { value: 'Cotaparaco', label: 'Cotaparaco' },
        { value: 'Huayllapampa', label: 'Quinuabamba' },
        { value: 'Llacllín', label: 'Llacllín' },
        { value: 'Marca', label: 'Marca' },
        { value: 'Pampas Chico', label: 'Pampas Chico' },
        { value: 'Pararín', label: 'Pararín' },
        { value: 'Tapacocha', label: 'Tapacocha' },
        { value: 'Ticapampa', label: 'Ticapampa' },
    ],



};