interface Option {
    value: string;
    label: string;
}
const ProvinciaPorDepartamento: Record<string, Option[]> = {
    Amazonas: [
        { value: 'Bagua', label: 'Bagua' },
        { value: 'Bongorá', label: 'Bongorá' },
        { value: 'Condorcanqui', label: 'Condorcanqui' },
        { value: 'Chachapoyas', label: 'Chachapoyas' },
        { value: 'Luya', label: 'Luya' },
        { value: 'Rodriguez de mendoza', label: 'Rodriguez de Mendoza' },
        { value: 'Utcubamba', label: 'Utcubamba' },
    ],
    Ancash: [
        { value: 'Aija', label: 'Aija' },
        { value: 'Antonio Raymondi', label: 'Antonio Raymondi' },
        { value: 'Asuncion', label: 'Asunción' },
        { value: 'Bolognesi', label: 'Bolognesi' },
        { value: 'Carhuaz', label: 'Carhuaz' },
        { value: 'Carlos Fitzcarrald', label: 'Carlos Fitzcarrald' },
        { value: 'Casma', label: 'Casma' },
        { value: 'Corongo', label: 'Corongo' },
        { value: 'Huaraz', label: 'Huaraz' },
        { value: 'Huari', label: 'Huari' },
        { value: 'Huarmey', label: 'Huarmey' },
        { value: 'Huaylas', label: 'Huaylas' },
        { value: 'Mariscal Luzuriaga', label: 'Mariscal Luzuriaga' },
        { value: 'Ocros', label: 'Ocros' },
        { value: 'Pallasca', label: 'Pallasca' },
        { value: 'Pomabamba', label: 'Pomabamba' },
        { value: 'Recuay', label: 'Recuay' },
        { value: 'Santa', label: 'Santa' },
        { value: 'Sihuas', label: 'Sihuas' },
        { value: 'Yungay', label: 'Yungay' },
    ],
    Apurimac: [
        { value: 'Abancay', label: 'Abancay' },
        { value: 'Andahuaylas', label: 'Andahuaylas' },
        { value: 'Antabamba', label: 'Antabamba' },
        { value: 'Aymaraes', label: 'Aymaraes' },
        { value: 'Cotabambas', label: 'Cotabambas' },
        { value: 'Grau', label: 'Grau' },
        { value: 'Chincheros', label: 'Chincheros' },
    ],
    Arequipa: [
        { value: 'Arequipa', label: 'Arequipa' },
        { value: 'Camana', label: 'Camaná' },
        { value: 'Castilla', label: 'Castilla' },
        { value: 'Caraveli', label: 'Caravelí' },
        { value: 'Caylloma', label: 'Caylloma' },
        { value: 'Condesuyos', label: 'Condesuyos' },
        { value: 'Islay ', label: 'Islay ' },
        { value: 'Union', label: 'La Unión' },
    ],
    Ayacucho: [
        { value: 'Huamanga', label: 'Huamanga' },
        { value: 'Cangallo', label: 'Cangallo' },
        { value: 'Huanca_Sancos', label: 'Huanca Sancos' },
        { value: 'Huanta', label: 'Huanta' },
        { value: 'La Mar', label: 'La Mar' },
        { value: 'Lucanas', label: 'Lucanas' },
        { value: 'Parinacochas', label: 'Parinacochas' },
        { value: 'Paucar de la Sara Sara', label: 'Páucar de Sara Sara' },
        { value: 'Sucre', label: 'Sucre' },
        { value: 'Victor Fajardo', label: 'Victor Fajardo' },
        { value: 'Vilcashuaman', label: 'Vilcashuaman' },
    ],
    Cajamarca: [
        { value: 'Cajamarca', label: 'Cajamarca' },
        { value: 'Cajabamba', label: 'Cajabamba' },
        { value: 'Celendin', label: 'Celendin' },
        { value: 'Chota', label: 'Chota' },
        { value: 'Contumaza', label: 'Contumaza' },
        { value: 'Cutervo', label: 'Cutervo' },
        { value: 'Hualgayoc', label: 'Hualgayoc' },
        { value: 'Jaen', label: 'Jaen' },
        { value: 'San Ignacio', label: 'San Ignacio' },
        { value: 'San Marcos', label: 'San Marcos' },
        { value: 'San Miguel', label: 'San Miguel' },
        { value: 'San Pablo', label: 'San Pablo' },
        { value: 'Santa Cruz', label: 'Santa Cruz' },
    ],
    Cusco: [
        { value: 'Acomayo', label: 'Acomayo' },
        { value: 'Anta', label: 'Anta' },
        { value: 'Calca', label: 'Calca' },
        { value: 'Canas', label: 'Canas' },
        { value: 'Canchis', label: 'Canchis' },
        { value: 'Chumbivilcas', label: 'Chumbivilcas' },
        { value: 'Espinar', label: 'Espinar' },
        { value: 'La Convencion', label: 'La Convencion' },
        { value: 'Paruro', label: 'Paruro' },
        { value: 'Paucartambo', label: 'Paucartambo' },
        { value: 'Quispicanchi', label: 'Quispicanchi' },
        { value: 'Urubamba', label: 'Urubamba' },
    ],
    Huancavelica: [
        { value: 'Huancavelica', label: 'Huancavelica' },
        { value: 'Tayacaja', label: 'Tayacaja' },
        { value: 'Angaraes', label: 'Angaraes' },
        { value: 'Acocabamba', label: 'Acocabamba' },
        { value: 'Churcampa', label: 'Churcampa' },
        { value: 'Huaytara', label: 'Huaytara' },
        { value: 'Castrovirreyna', label: 'Castrovirreyna' },
    ],
    Huanuco: [
        { value: 'Huanuco', label: 'Huanuco' },
        { value: 'Ambo', label: 'Ambo' },
        { value: 'Dos de Mayo', label: 'Dos de Mayo' },
        { value: 'Huacaybamba', label: 'Huacaybamba' },
        { value: 'Huamalies', label: 'Huamalies' },
        { value: 'Leoncio Prado', label: 'Leoncio Prado' },
        { value: 'Marañon', label: 'Marañon' },
        { value: 'Pachitea', label: 'Pachitea' },
        { value: 'Puerto Inca', label: 'Puerto Inca' },
        { value: 'Lauricocha', label: 'Lauricocha' },
        { value: 'Yarowilca', label: 'Yarowilca' },
    ],
    Ica: [
        { value: 'Ica', label: 'Ica' },
        { value: 'Chincha', label: 'Chincha' },
        { value: 'Nasca', label: 'Nasca' },
        { value: 'Palpa', label: 'Palpa' },
        { value: 'Pisco', label: 'Pisco' },
    ],
    Junín: [
        { value: 'Huancayo', label: 'Huancayo' },
        { value: 'Concepcion', label: 'Concepcion' },
        { value: 'Chanchamayo', label: 'Chanchamayo' },
        { value: 'Jauja', label: 'Jauja' },
        { value: 'Junin', label: 'Junin' },
        { value: 'Satipo', label: 'Satipo' },
        { value: 'Tarma', label: 'Tarma' },
        { value: 'Yauli', label: 'Yauli' },
        { value: 'Chupaca', label: 'Chupaca' },
    ],
    'La Libertad': [
        { value: 'Trujillo', label: 'Huancayo' },
        { value: 'Ascope', label: 'Ascope' },
        { value: 'Bolivar', label: 'Bolivar' },
        { value: 'Chepén', label: 'Chepén' },
        { value: 'Julcán', label: 'Julcán' },
        { value: 'Otuzco', label: 'Otuzco' },
        { value: 'Pacasmayo', label: 'Pacasmayo' },
        { value: 'Pataz', label: 'Pataz' },
        { value: 'Sanchéz Carrion', label: 'Sanchéz Carrion' },
        { value: 'Santiago de Chuco', label: 'Santiago de Chuco' },
        { value: 'Gran Chimú', label: 'Gran Chimú' },
        { value: 'Virú', label: 'Virú' },
    ],
    Lambayeque: [
        { value: 'Chiclayo', label: 'Chiclayo' },
        { value: 'Ferreñafe', label: 'Ferreñafe' },
        { value: 'Lambayeque', label: 'Lambayeque' },
    ],
    Lima: [
        { value: 'Barranca', label: 'Barranca' },
        { value: 'Cajatambo', label: 'Cajatambo' },
        { value: 'Canta', label: 'Canta' },
        { value: 'Cañete', label: 'Cañete' },
        { value: 'Huaral', label: 'Huaral' },
        { value: 'Huarochirí', label: 'Huarochirí' },
        { value: 'Huaura', label: 'Huaura' },
        { value: 'Oyón', label: 'Oyón' },
        { value: 'Yauyos', label: 'Yauyos' },
    ],
    Loreto: [
        { value: 'Maynas', label: 'Maynas' },
        { value: 'Alto Amazonas', label: 'Alto Amazonas' },
        { value: 'Loreto-Nauta', label: 'Loreto-Nauta' },
        { value: 'Mariscal Ramón Castilla', label: 'Mariscal Ramón Castilla' },
        { value: 'Requena', label: 'Requena' },
        { value: 'Ucayali', label: 'Ucayali' },
        { value: 'Datem del Marañon', label: 'Datem del Marañon' },
        { value: 'Putumayo', label: 'Putumayo' },
    ],
    'Madre de Dios': [
        { value: 'Tambopata', label: 'Tambopata' },
        { value: 'Puerto Maldonado', label: 'Puerto Maldonado' },
        { value: 'Tahuamanu', label: 'Tahuamanu' },
    ],
    Moquegua: [
        { value: 'Mariscal Nieto', label: 'Mariscal Nieto' },
        { value: 'General Sánchez Cerro', label: 'General Sánchez Cerro' },
        { value: 'Ilo', label: 'Ilo' },
    ],
    Pasco: [
        { value: 'Pasco', label: 'Pasco' },
        { value: 'Daniel Alcides Carrión', label: 'Daniel Alcides Carrión' },
        { value: 'Oxapampa', label: 'Oxapampa' },
    ],
    Piura: [
        { value: 'Piura', label: 'Piura' },
        { value: 'Ayabaca', label: 'Ayabaca' },
        { value: 'Huancabamba', label: 'Huancabamba' },
        { value: 'Morropón', label: 'Morropón' },
        { value: 'Paita', label: 'Paita' },
        { value: 'Sullana', label: 'Sullana' },
        { value: 'Talara', label: 'Talara' },
        { value: 'Sechura', label: 'Sechura' },
    ],
    Puno: [
        { value: 'San Román', label: 'San Román' },
        { value: 'Puno', label: 'Puno' },
        { value: 'Azángaro', label: 'Azángaro' },
        { value: 'Chucuito', label: 'Chucuito' },
        { value: 'Carabaya', label: 'Carabaya' },
        { value: 'Melgar', label: 'Melgar' },
        { value: 'El Collado', label: 'El Collado' },
        { value: 'Huancané', label: 'Huancané' },
        { value: 'Sandia', label: 'Sandia' },
        { value: 'Lampa', label: 'Lampa' },
        { value: 'Yunguyo', label: 'Yunguyo' },
        { value: 'San Antonio de Putina', label: 'San Antonio de Putina' },
        { value: 'Moho', label: 'Moho' },
    ],
    'San Martín': [
        { value: 'Moyobamba', label: 'Moyobamba' },
        { value: 'Bellavista', label: 'Bellavista' },
        { value: 'El Dorado', label: 'El Dorado' },
        { value: 'Huallaga', label: 'Huallaga' },
        { value: 'Lamas', label: 'Lamas' },
        { value: 'Mariscal Cáceres', label: 'Mariscal Cáceres' },
        { value: 'Picota', label: 'Picota' },
        { value: 'Rioja', label: 'Rioja' },
        { value: 'San Mártin', label: 'San Martín' },
        { value: 'Tocache', label: 'Tocache' },
    ],
    Tacna: [
        { value: 'Tacna', label: 'Tacna' },
        { value: 'Tarata', label: 'Tarata' },
        { value: 'Jorge Basadre', label: 'Jorge Basadre' },
        { value: 'Candarave', label: 'Candarave' },
    ],
    Tumbes: [
        { value: 'Tumbes', label: 'Tumbes' },
        { value: 'Zarumilla', label: 'Zarumilla' },
        { value: 'Contralmirante Villar', label: 'Contralmirante Villar' },
    ],
    Ucayali: [
        { value: 'Coronel Portillo', label: 'Coronel Portillo' },
        { value: 'Atalaya', label: 'Atalaya' },
        { value: 'Padre Abad', label: 'Padre Abad' },
        { value: 'Purús', label: 'Purús' },
    ],

    
};


export { ProvinciaPorDepartamento };